<?php

/**
 * Implements hook_theme().
 */
function client_admin_theme($existing, $type, $theme, $path) {
  return [
    // Name of the theme hook. This is used in the controller to trigger the hook.
    'client_admin_theme__landing_page' => [
      'render element' => 'children',
      // If no template name is defined here,
      // it defaults to the name of the theme hook,
      // ie. module-name-theme-hook.html.twig
      'template' => 'client-admin--landing-page',
      // Optionally define path to Twig template files.
      // Defaults to the module's ./templates/ directory.
      'path' => $path . '/templates',
      // Optionally define variables that will be passed to the Twig
      // template and set default values for them.
      'variables' => [
        'variable1' => 'Yet another default text.',
        'variable2' => 0,
        'variable3' => [0, 0, 0],
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function client_admin_preprocess_block(&$variables) {
  $t = $variables;
}

function client_admin_node_alter() {

}
